<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Главное меню</title>
</head>
<body>
<form action="/orders">
    <button>Заказы</button>
</form>
<form action="/purchases">
    <button>Закупки</button>
</form>
<form action="/products">
    <button>Товары</button>
</form>
<form action="/stock">
    <button>Склад</button>
</form>
<form action="/clients">
    <button>Клиенты</button>
</form>
<form action="/users">
    <button>Сотрудники</button>
</form>
</body>
</html>